# Generated by Django 5.2.1 on 2025-05-22 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appl_name', models.CharField(max_length=50, verbose_name='Applicant name')),
                ('appl_surname', models.CharField(max_length=100, verbose_name='Applicant surname')),
                ('appl_email', models.EmailField(max_length=100, verbose_name='Applicant email')),
                ('appl_address', models.CharField(max_length=200, verbose_name='Applicant address')),
                ('appl_phone', models.CharField(max_length=15, verbose_name='Applicant phone')),
                ('appl_birthdate', models.DateField(verbose_name='Applicant birthday')),
                ('appl_submitted', models.DateTimeField(auto_now=True)),
                ('appl_notes', models.TextField(blank=True, default='', max_length=1500, null=True, verbose_name='Other notes')),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100, verbose_name='Job name')),
                ('job_desc', models.CharField(max_length=2000, verbose_name='Job description')),
                ('job_open_from', models.DateField(verbose_name='Valid from')),
                ('job_open_to', models.DateField(verbose_name='Valid to')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_name', models.CharField(max_length=30, unique=True)),
                ('stat_order', models.IntegerField(default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_salary', models.IntegerField(verbose_name='Salary ($)')),
                ('emp_position', models.CharField(max_length=50, verbose_name='Employee position')),
                ('emp_applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.jobapplicant', verbose_name='Applicant')),
            ],
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='appl_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.joboffer', verbose_name='Applies for'),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='appl_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.recruitmentstatus', verbose_name='Applicant status'),
        ),
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shi_salary', models.IntegerField(verbose_name='Salary ($)')),
                ('shi_month', models.DateField(verbose_name='Payday')),
                ('shi_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee', verbose_name='Employee')),
            ],
        ),
    ]
