# Generated by Django 5.2.1 on 2025-05-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'History Trouble', 'verbose_name_plural': 'History Troubles'},
        ),
        migrations.AlterModelOptions(
            name='jobapplicant',
            options={'verbose_name': 'Trouble done', 'verbose_name_plural': 'Trouble done'},
        ),
        migrations.AlterModelOptions(
            name='joboffer',
            options={'verbose_name': 'Current Trouble', 'verbose_name_plural': 'Current Troubles'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_position',
            field=models.CharField(max_length=50, verbose_name='History Trouble'),
        ),
        migrations.AlterField(
            model_name='jobapplicant',
            name='appl_name',
            field=models.CharField(max_length=50, verbose_name='Trouble done'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='job_name',
            field=models.CharField(max_length=100, verbose_name='Current Trouble'),
        ),
    ]
