# Generated by Django 5.2.1 on 2025-05-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_remove_joboffer_job_desc_remove_joboffer_job_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='customer',
            field=models.CharField(blank=True, choices=[('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Red', 'Red'), ('Black', 'Black')], max_length=100, null=True),
        ),
    ]
