# Generated by Django 5.2.1 on 2025-05-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_joboffer_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='actual_handling_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Duration Penanganan Real (Waktu real penanganan)'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='case_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='No Case (Nomor kasus/laporan gangguan)'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='customer',
            field=models.CharField(blank=True, choices=[('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Red', 'Red'), ('Black', 'Black')], max_length=100, null=True, verbose_name='NCAL (Nama pelanggan/akun)'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Duration (Lama gangguan)'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='duration_waneda',
            field=models.DurationField(blank=True, null=True, verbose_name='Duration (waneda)'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='end_pause_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Pause (Waktu jeda selesai)'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End (Waktu gangguan selesai)'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='issue_classification',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Klasifikasi Gangguan (Kategori teknis)'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='last_action',
            field=models.TextField(blank=True, null=True, verbose_name='Action Terakhir (Langkah terakhir)'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note (Catatan tambahan)'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='odp_or_bts',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ODP/BTS (Lokasi teknis)'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='pause_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Duration Pause (Durasi jeda)'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='power_after',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Power After (Status daya sesudah)'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='power_before',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Power Before (Status daya sebelum)'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='priority',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Priority (Tingkat urgensi gangguan)'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='problem_summary',
            field=models.TextField(blank=True, null=True, verbose_name='Problem (Ringkasan masalah)'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='root_cause',
            field=models.TextField(blank=True, null=True, verbose_name='Penyebab (Penyebab gangguan)'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='severity_level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Level (Level/skala gangguan)'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='site_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Site (Nama lokasi pelanggan)'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='start_escalation_waneda',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Escalation (waneda)'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='start_pause_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Pause (Waktu jeda mulai)'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start (Tanggal & waktu mulai gangguan)'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status (Status penanganan)'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='technician',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TS (Teknisi yang menangani)'),
        ),
    ]
