# Generated by Django 5.2.1 on 2025-05-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_joboffer_actual_handling_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='priority',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10, null=True, verbose_name='Priority (Tingkat urgensi gangguan)'),
        ),
    ]
