# Generated by Django 5.2.1 on 2025-05-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_joboffer_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='odp_or_bts',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='segmen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Segmen'),
        ),
    ]
