# Generated by Django 5.2.1 on 2025-05-22 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_remove_joboffer_odp_or_bts_joboffer_segmen'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobUpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_support', models.CharField(max_length=100, verbose_name='Technical Support')),
                ('penyebab', models.TextField(verbose_name='Penyebab')),
                ('action', models.TextField(verbose_name='Action')),
                ('start_escalation_vendor', models.DateTimeField(blank=True, null=True, verbose_name='Start Eskalasi ke Vendor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_histories', to='hr.joboffer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
