# Generated by Django 5.2.1 on 2025-05-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_jobupdatehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='close_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Durasi Close Trouble'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='close_escalation_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Durasi Close Eskalasi Vendor'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='close_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Close Time'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Closed'),
        ),
    ]
